# Generated by Django 4.2.7 on 2025-07-08 20:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome Carta')),
                ('card_type', models.CharField(choices=[('character', 'Personaggio'), ('weapon', 'Arma'), ('room', 'Stanza')], max_length=20, verbose_name='Tipo Carta')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Codice Carta')),
                ('icon', models.CharField(default='fas fa-question', max_length=50, verbose_name='Icona FontAwesome')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Carte',
                'ordering': ['card_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome Sessione')),
                ('session_code', models.CharField(max_length=6, unique=True, verbose_name='Codice Sessione')),
                ('host_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Host')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('max_players', models.IntegerField(default=6, verbose_name='Max Giocatori')),
                ('allow_card_sharing', models.BooleanField(default=True, verbose_name='Permetti Condivisione Carte')),
                ('auto_reveal_cards', models.BooleanField(default=False, verbose_name='Rivela Carte Automaticamente')),
            ],
            options={
                'verbose_name': 'Sessione di Gioco',
                'verbose_name_plural': 'Sessioni di Gioco',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome Giocatore')),
                ('character', models.CharField(choices=[('colonel_mustard', 'Colonnello Mustard'), ('miss_scarlett', 'Miss Scarlett'), ('professor_plum', 'Professor Plum'), ('mrs_peacock', 'Mrs. Peacock'), ('mr_green', 'Mr. Green'), ('mrs_white', 'Mrs. White')], max_length=20, verbose_name='Personaggio')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('is_host', models.BooleanField(default=False, verbose_name='È Host')),
                ('personal_notes', models.TextField(blank=True, verbose_name='Note Personali')),
                ('share_cards_publicly', models.BooleanField(default=True, verbose_name='Condividi Carte Pubblicamente')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='cluedo_game.gamesession')),
            ],
            options={
                'verbose_name': 'Giocatore',
                'verbose_name_plural': 'Giocatori',
                'ordering': ['joined_at'],
                'unique_together': {('session', 'character')},
            },
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('player_joined', 'Giocatore si è unito'), ('player_left', 'Giocatore è uscito'), ('card_added', 'Carta aggiunta'), ('card_removed', 'Carta rimossa'), ('card_shared', 'Carta condivisa'), ('knowledge_updated', 'Conoscenza aggiornata'), ('note_added', 'Nota aggiunta'), ('session_created', 'Sessione creata'), ('session_ended', 'Sessione terminata')], max_length=20)),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dati Extra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cluedo_game.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cluedo_game.gamesession')),
            ],
            options={
                'verbose_name': 'Log di Gioco',
                'verbose_name_plural': 'Log di Gioco',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_type', models.CharField(choices=[('reveal', 'Rivela Carta'), ('hint', 'Suggerimento'), ('question', 'Domanda'), ('deduction', 'Deduzione')], max_length=15)),
                ('message', models.TextField(verbose_name='Messaggio')),
                ('is_public', models.BooleanField(default=False, verbose_name='Visibile a Tutti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo_game.card')),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_from', to='cluedo_game.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_shares', to='cluedo_game.gamesession')),
                ('to_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_to', to='cluedo_game.player')),
            ],
            options={
                'verbose_name': 'Condivisione Carta',
                'verbose_name_plural': 'Condivisioni Carte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_card', models.BooleanField(default=False, verbose_name='Ha la Carta')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visibile ad Altri')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo_game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cluedo_game.player')),
            ],
            options={
                'verbose_name': 'Carta Giocatore',
                'verbose_name_plural': 'Carte Giocatori',
                'unique_together': {('player', 'card')},
            },
        ),
        migrations.CreateModel(
            name='CardKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_type', models.CharField(choices=[('has', 'Ha la carta'), ('not_has', 'Non ha la carta'), ('unknown', 'Sconosciuto'), ('maybe', 'Forse ha'), ('probably_not', 'Probabilmente non ha')], default='unknown', max_length=15)),
                ('confidence', models.IntegerField(default=50, help_text='Livello di confidenza (0-100)')),
                ('notes', models.TextField(blank=True, verbose_name='Note sulla Deduzione')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Condiviso con Altri')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluedo_game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='cluedo_game.player')),
                ('target_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_by', to='cluedo_game.player')),
            ],
            options={
                'verbose_name': 'Conoscenza Carta',
                'verbose_name_plural': 'Conoscenze Carte',
                'unique_together': {('player', 'target_player', 'card')},
            },
        ),
    ]
